services:
  frontend:
    build: .
    container_name: frontend_app
    working_dir: /app
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
      - playwright_cache:/root/.cache/ms-playwright
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  frontend_node_modules:
  playwright_cache: